[Rainmeter]
Update=1000
MiddleMouseDownAction=!RainmeterDeactivateConfig
DynamicWindowSize=1
AccurateText=1

;;  Uncomment the lines below for positional debugging
;;	Using BackGroundMode: 
;;		* 0 disables the skin background
;;		* 2 enables a solid or gradient background (by uncommenting SolidColor and SolidColor2)
BackgroundMode=0

;; 	Increasing the fourth variable above changes opacity of a grey box which makes the whole area draggable/clickable
SolidColor=160,160,160,1
;SolidColor2=0,0,255,#PostitionalDebugOpacity#
....................................................................................................................................................

[Metadata]
Author=Jehan Alvani
Information= This was adapted from "Custom Mii System Skin v2", which was | authored by abu46 and provided without license.
Version=.5
License=MIT License (see Clarity\license.txt)